# Generated by Django 6.0.5 on 2026-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('feast_day', models.DateField(blank=True, null=True)),
                ('biography', models.TextField()),
                ('quote', models.TextField(help_text='Famous quote or saying')),
                ('image', models.ImageField(blank=True, null=True, upload_to='saints/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
