# Generated by Django 6.0.5 on 2026-05-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('prayer', models.TextField()),
                ('saint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.saint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
