# Generated by Django 6.0.5 on 2026-05-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(help_text='The date this content is for', unique=True)),
                ('image', models.ImageField(blank=True, help_text='Daily changing image', null=True, upload_to='daily_content/')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Daily Content',
                'verbose_name_plural': 'Daily Contents',
                'ordering': ['-date'],
            },
        ),
    ]
