# Generated by Django 6.0.5 on 2026-05-15 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCommemoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(help_text='ቀን', unique=True)),
                ('content_am', models.TextField(help_text='የእለቱ የቅዱሳን መታሰቢያ ጽሁፍ (Amharic only)')),
            ],
            options={
                'verbose_name': 'Daily Commemoration',
                'verbose_name_plural': 'Daily Commemorations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CommemorationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='commemorations/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('commemoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.dailycommemoration')),
            ],
            options={
                'verbose_name': 'Commemoration Image',
                'verbose_name_plural': 'Commemoration Images',
            },
        ),
    ]
