# Generated by Django 6.0.5 on 2026-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailycommemoration_commemorationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycommemoration',
            name='quote_am',
            field=models.TextField(blank=True, default='', help_text='ልዩ ጥቅስ / የተወሰደ ትምህርት (quote with special style)'),
        ),
        migrations.AddField(
            model_name='dailycommemoration',
            name='quote_source_am',
            field=models.CharField(blank=True, default='', help_text='የጥቅሱ ምንጭ (quote source)', max_length=300),
        ),
        migrations.AddField(
            model_name='dailycommemoration',
            name='title_am',
            field=models.CharField(blank=True, default='', help_text='ርዕስ (Amharic title)', max_length=300),
        ),
    ]
