# Generated by Django 6.0.5 on 2026-05-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailycommemoration_quote_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycommemoration',
            name='content_am',
            field=models.TextField(blank=True, default='', help_text='ተራ ጽሁፍ (plain text - optional if using sections below)'),
        ),
        migrations.AlterField(
            model_name='dailycommemoration',
            name='quote_am',
            field=models.TextField(blank=True, default='', help_text='ልዩ ጥቅስ / የተወሰደ ትምህርት (quote)'),
        ),
        migrations.CreateModel(
            name='CommemorationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section_type', models.CharField(choices=[('heading', '✝ Heading'), ('subheading', '☞ Subheading'), ('quote', '📖 Quote'), ('text', 'Text'), ('sub', '° Sub Text')], default='text', max_length=20)),
                ('content', models.TextField(help_text='ይህን ክፍል ውስጥ የሚፈልጉትን ጽሁፍ ያስገቡ')),
                ('order', models.PositiveIntegerField(default=0)),
                ('commemoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.dailycommemoration')),
            ],
            options={
                'verbose_name': 'Content Section',
                'verbose_name_plural': 'Content Sections',
                'ordering': ['order'],
            },
        ),
    ]
